Helo Microverse!
sergio-usma/hello-microverse pull request #3
Opened 2023-03-21 23:10 UTC by sergio-usma

This project reviewed some functionalities of linters, GIT, and GitHub, fulfilling the requirements of the activity:
- Created a new GitHub repo.
- Created a new branch according to the GitHub flow rules.
- Added a .gitignore file.
- Added node_modules to the gitignore file.
- Set up a linter for HTML and CSS making sure that any files that were not relevant were ignored by git.
- Added a descriptive README file to the project using a customized template.
- Added 3 files (each one in a separate commit):
- An HTML file that included a header with the text "Hello Microverse!" using h1 tag.
- A CSS file that included one class with styles for the header in my favorite color.
- A test.md file with the text "This file should be ignored by git".
- Opened a pull request.

2023-03-21 23:33 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @sergio-usma ,
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
 :heavy_check_mark: Linters are passing.
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Your linters are correct.
 
 ## Required Changes 
_Check Under the Review

If you need any suggestion from me I suggest you to use tabindex in your headings paragraph tags to make text . :upside_down_face:
 
 ## Optional suggestions 

- [ ]Check_under the review 

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 23:33 UTC, Alfredbis29 commented on README.md
> +  <img src="./murple_logo.png" alt="logo" width="140"  height="auto" />
- [ ] Great work so far for this project , kindly remove the template logo and use your own logo for your project to look more professional :wink:

2023-03-21 23:33 UTC, Alfredbis29 commented on README.md
> +### Setup
- [ ] I can see that you tried to give the way on how we can setup the project in our local machine but you did provide the Project Link which we are going to clone , kindly add it for being more specific on how to setup the project :smile:

2023-03-21 23:33 UTC, Alfredbis29 commented on README.md
> +--->
- [Optional ]Kindly remove unused comments in your Readme and customize it on your own :wink:

2023-03-24 22:12 UTC, sergio-usma commented on README.md
> +  <img src="./murple_logo.png" alt="logo" width="140"  height="auto" />
Updated!

2023-03-24 22:12 UTC, sergio-usma commented on README.md
> +### Setup
Updated!

2023-03-24 22:12 UTC, sergio-usma commented on README.md
> +--->
Updated! Thank you very much for the feedback!

2023-03-24 22:20 UTC, divinecharlotte approved these changes
# Hello @sergio-usma    😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 
### To Highlight 💯

- No linters errors ✔️
- Descriptive PR ✔️
- Descriptive commit messages 👍 





## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-25 01:37 UTC, merged